

services:
  proyecto4:
    build: ./
    ports:
      - "3001:3000"
    env_file:
      - .env
    depends_on:
      - postgresdb
    networks:
      - nestNetwork
    


  postgresdb:
    image: postgres

    networks:
      - nestNetwork

    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pgdata:

networks:
    nestNetwork:
      driver: bridge
